### ISSUE TITLE
The plugin doesn´t work

### ISSUE THREAD

**Issue by Dari-OS** [Photon-GitHub/AntiCheatAddition#514]
I bought AntiCheatAddition yesterday but none of the moduls?
I tryed ant-autofish,esp,..., and the anticheat just did nothing

**Comment by Photon-GitHub** [comment]
Please post your ACA config, and your ACA log files.
If ACA does not do anything it is likely that it did not start up, either because there was a config loading error, or you forgot to install ProtocolLib.

**Comment by DariDOSS** [comment]
908
    # This will detect Winterware.
909
    Winterware:
910
      # Do you want to enable Winterware-Sentinel?
911
      enabled: true
912
      # The channels AntiCheatAddition will listen to.
913
      incoming_channels:
914
        - "lc:brand"
915
        - "LC|Brand"
916
      # All strings in this list will need to be included in the message sent in the channels above to trigger the
917
      # commands. An empty list defined as [ ] means any message is accepted by containsAll.
918
      containsAll: [ ]
919
      # At least one string in this list will need to be included in the message sent in the channels above to trigger
920
      # the commands. An empty list defined as [ ] means any message is accepted by containsAny.
921
      containsAny: [ ]
922
      # What commands will be executed if the mod is detected.
923
      # Automatic banning can be considered.
924
      commands:
925
        - "kick {player} Illegal Client Modifications"
926
# ------------------------------------------------------------------------------------------------------------------- #
927
#                                               ___      _                                                            #
928
#                                              |   \ ___| |__ _  _ __ _                                               #
929
#                                              | |) / -_) '_ \ || / _` |                                              #
930
#                                              |___/\___|_.__/\_,_\__, |                                              #
931
#                                                                 |___/                                               #
932
#                                                                                                                     #
933
# ------------------------------------------------------------------------------------------------------------------- #
934
​
935
# Allows defining where to send debug messages to. Please note that when reporting bugs, you will need to provide the
936
# debug file of AntiCheatAddition, therefore this setting is enabled here.
937
Debug:
938
  # Do you want AntiCheatAddition to log into a log-file?
939
  file: true
940
  # Should players be able to get debug messages if they have the anticheataddition.debug permission
941
  # Players can toggle the debug output with the command /anticheataddition debug
942
  players: false
943
  # Should the debug output be logged in the console (very spammy, only recommended for testing purposes)
944
  console: false
  
  this is the config

**Comment by Photon-GitHub** [comment]
I don't think that was what you intended. Please use a service like pastebin.

**Comment by DariDOSS** [comment]
https://pastebin.com/E6E6t7BS

**Comment by Photon-GitHub** [comment]
Seems fine.
What about the ACA or server startup log?

**Comment by iFlamingoz** [comment]
You might also just have bypass permissions.

**Comment by DariDOSS** [comment]
> Seems fine. What about the ACA or server startup log?

https://pastebin.com/7H182CSr

**Comment by Photon-GitHub** [comment]
So, either you have bypass permissions, or you are using Bedrock edition (which is bypassed via floodgate).
Make sure you use the latest version of ACA and you do not have op.

**Comment by DariDOSS** [comment]
> So, either you have bypass permissions, or you are using Bedrock edition (which is bypassed via floodgate). Make sure you use the latest version of ACA and you do not have op.

I am using Java and deoped me but all the moduls wont work

**Comment by Photon-GitHub** [comment]
As the startup log states the modules are loading successfully and without error. 
Therefore, if no modules work, you are likely to be bypasses (permissions or op). Make sure that no permissions plugin is somehow giving you the permission anticheataddition.bypass.*.

If you want to see any detections in console, make sure to set the respective debug setting to true at the bottom of the config, otherwise ACA will be silent until a command threshold is reached. 
Another option is using the /aca info <player> command, as that prints the exact vls of the player.

Try some very obvious and instantly detectable module like any instantaneous cheststealer or fast tower / scaffold. If you do not see any vls, you likely have some bypass permission. I generally recommend testing with a seperate minecraft account so you do not have those problems.

Also, ESP does not allow for any detections, so you should only see reduced information if you test it and the other player is e.g. hidden behind a tree (or none at all if they are sneaking).
