### ISSUE TITLE
ESP check does not work

### ISSUE THREAD

**Issue by Coquettishpig** [Photon-GitHub/AntiCheatAddition#540]
purpur-1.18.2-1632

java17

**Comment by Janmm14** [comment]
the esp check is not a check. it does hide other players if they have no line of sight; it does not check every block in the line of sight, only probes, mostly near each entity and not that much in the middle.

so if at some distances between you and each other player: if there is a block. it hides the target player.
due to performance problems it cannot check more detailed.

**Comment by Photon-GitHub** [comment]
Janmm14's answer is correct. If that is not working on your server, please add more information what exactly is not working and in which circumstances. There will be no detections as ESP is a completely clientside cheat that cannot be detected in any way and only uses the information sent to the client to render additional information.

**Comment by Coquettishpig** [comment]
![image](https://user-images.githubusercontent.com/107100449/209819050-c8216a80-22cb-4bdf-b17c-29a203a63739.png)
但是即使被方块遮挡或者蹲下，也不起作用

**Comment by Coquettishpig** [comment]
> 但是即使被方块遮挡或者蹲下，也不起作用 ![image](https://user-images.githubusercontent.com/107100449/209819173-c4a23ce8-a091-4ad6-94a8-2286b0363e88.png)

即使我是正常客户端，也仍然可以看见玩家的名字
![image](https://user-images.githubusercontent.com/107100449/209819490-015347ee-04ad-4fff-ac23-52090cd4a8b0.png)

**Comment by Photon-GitHub** [comment]
I am afraid I am not speaking Chinese, so I can only work with the translation results of a machine translation. 

First and foremost, double-check that ESP.enabled is set to true. Please don't laugh, this has actually been the problem in various issues. 

Once you have done that there are a few details of the check that might interfere here:
In general, as you can read in the config, ESP does not hide standing players. This is because the nametag can be seen in vanilla minecraft even through blocks except when sneaking. If you want to enforce hiding players regardless of nametags make sure to set only_full_hide: true in the config.

Apart from that, I do not do a full raytrace to check whether a player can see another as that is too costly regarding performance. Instead, I only use a heuristic to check certain locations between the players. It should not be a problem in your case, as I check the blocks directly next to players, but maybe move around a bit and see if the player is hidden.

**Comment by Photon-GitHub** [comment]
If this bug is still relevant, feel free to reopen the issue.
