### ISSUE TITLE
[SUGGESTION] Reload config command.

### ISSUE THREAD

**Issue by Regomy** [Photon-GitHub/AntiCheatAddition#572]
I suggest adding a command to reload the config.

**Comment by Photon-GitHub** [comment]
I will sadly not add this for several reasons:
- ACA's config is very powerful and you can add custom checks in Sentinel. Making that config section alone reloadable will be a hard endavour due to the architecture of my plugin.
- I generally think that if you have to reload regularly it is a problem with the config. I strive to make it readable and work without many value changes.
- There are quite a few performance optimizations that are only available if a loaded value never changes. 

That said, if you have any problems or suggestions for the config, please let me know.
