### ISSUE TITLE
🟡 | Teaming check false flags / suggestions

### ISSUE THREAD

**Issue by Regomy** [Photon-GitHub/AntiCheatAddition#648]
**False flags:**

1) Players under the invisibility potion are not always visible, which means that 2 unsuspecting invisible players will be around - they will be detected.

2) Some Bedwars can issue a dead (hidePlayer) /vanish, which means that another player will not see that one, but they will be marked for teaming.

3) What if one player builds up something like obsidian and the other player breaks it xxx time? They'll get tagged.

~ With the current NOT customizable infraction system, we can't force anti-chit to not clear infractions for teaming during... say an hour, so by issuing a quick kick for teaming we risk kicking regular players out of the game.

**Suggestions:**
1) In config: Add a time after teleportation that players will not be checked.
2) In config: If both players do not move or are behind an obstacle do not check them.
3) In config: only issue infractions if “lulled players” are hitting another player together, not just being close to each other.
4) In config: the ability to exclude players with the same ip from checking,
5) Do not check players in vehicles.

~ The problem is that because of one idiot, an innocent player will suffer, and we can not give something other than a kick. (We can, but I won't suggest it here because you will reject it like some of my other ideas).

Translated by DeepL.

**Comment by Photon-GitHub** [comment]
Invisibility or block breaking is a problematic thing as you can still see particles and Teaming is not really made for gamemodes with such mechanics. The check is indended to be used for gamemodes like survivialgames or ffa. Even then, it should only be used as a heuristic for your staff to check out, as players can chase one another for a long time without hits on an open field. Therefore, I will not add most of your suggestions, and I do not recommend setting up kicks for this check.

Vanish, however, is often used and I have added a canSee check in 9.1.5 so that will be ignored in the future. This also works with ESP, which might achieve some of your other wishes.
