### ISSUE TITLE
🔴 | Scaffold telly bridge false flags

### ISSUE THREAD

**Issue by Regomy** [Photon-GitHub/AntiCheatAddition#659]
> **Video** Video: https://youtu.be/_8XuUa3JMDk
> **Client:** Client version: 1.8.9 OptiFine
> **Server:**  Server version: 1.8.8 PandaSpigot
> **Logs:**  [2024-08-21.log](https://github.com/user-attachments/files/16696067/2024-08-21.log)
> **ACA:** [AntiCheatAddition] Version: 9.1.7 last commit from master branch

**Comment by Photon-GitHub** [comment]
I think this is once more a case of unusual building practices that I won't cover to ensure that there are not countless bypasses. You can see yourself how often you "fell down" from your bridge while building. Why should anyone legit do that? If you do have such players, use the config to disable the affected submodules of Scaffold.

**Comment by MichaelKozlovOfficial** [comment]
Any professional players can do that, if your plugin can't fix false positives, why is it paid? that's why I never bought it and mvn clean package did it.
Use other anticheats, don't report him anymore.

**Comment by MichaelKozlovOfficial** [comment]
And for example, I'm laddering and I'm flagging, your anticheat is garbage.
You can't fix what everyone uses in bedwars.
https://github.com/Photon-GitHub/AntiCheatAddition/issues/622

**Comment by Photon-GitHub** [comment]
The issue here is that these building styles are mostly flagged by Scaffold Jumping. Quite a few servers want to completely block Jumping as it is usually used in obvious scaffold cheats. In your example, you jump a lot, build quite quickly and regularly completely change your view. If I allowed all that, that would be a good blueprint for a fast scaffold cheat (just with higher precision than you). Jumping already has quite lenient flagging, which only happens after some time to alleviate this.
 
@MichaelKozlovOfficial You did not buy ACA but expect me to fix your issues free of charge and call my work garbage. Feel free to fix the issue without making lots of bypasses available, you have access to the code.

**Comment by MichaelKozlovOfficial** [comment]
first: you are wrong because 90% of 1.8 servers on Bedwars  allow it and the same intave for example is not as false as your anticheat for scaffold.
Because you just don't know how to do anticheat, anyway, I'll just add the necessary checks myself in my private fork.

Secondly, why should I buy if the author will write the same thing that you did not buy and so if I buy and what the fuck will change? I would support the author only if he would make normal products.

**Comment by MichaelKozlovOfficial** [comment]
checks are basic and ideally done in a day

**Comment by MichaelKozlovOfficial** [comment]
We don't make a server for noobs, even a player who has been playing for a year knows how to build a server
